defaults:
  - env_settings: bm25_retrieval
  - benchmark: miniF2F_lean4_test_easy_to_hard
  - eval_settings: n_60_dfs_gpt_oss_20b_no_retrieve_no_ex # n_60_dfs_gpt4_o3_mini_no_retrieve_no_ex # n_60_dfs_gpt4_o_no_retrieve_no_ex # n_60_dfs_gpt4_o3_mini_no_retrieve_no_ex
  - prompt_settings: simplified_lean4_copra_math
  - override hydra/job_logging: 'disabled'

benchmark:
  timeout_per_theorem_in_secs: 600
eval_settings:
  max_tokens_per_action: 4500
  timeout_in_secs: 600
  proof_retries: 5
  temperature: 0.7
  max_steps_per_episode: 100
  # model_params:
  #   reasoning_effort: low
  #   reasoning_token_count: 500
